"use client";

import { useEffect, useState } from "react";
import AnimatedSection from "@/app/components/AnimatedSection";

export default function PrivacyPolicyPage() {
  const [heroVisible, setHeroVisible] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setHeroVisible(true), 100);
    return () => clearTimeout(t);
  }, []);

  return (
    <main>
      {/* Hero */}
      <section className="relative flex min-h-[35vh] items-center justify-center overflow-hidden bg-zinc-900 pt-24">
        <div
          className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 h-72 w-[500px] rounded-full opacity-15 blur-[120px]"
          style={{
            background: "radial-gradient(circle, #6343d4 0%, transparent 70%)",
          }}
        />
        <div className="relative z-[2] text-center px-6">
          <h1
            className="text-4xl font-extrabold text-white sm:text-5xl lg:text-6xl"
            style={{
              opacity: heroVisible ? 1 : 0,
              transform: heroVisible ? "translateY(0)" : "translateY(30px)",
              transition: "all 0.8s ease-out 0.2s",
              textShadow: "0 4px 24px rgba(0,0,0,0.5)",
            }}
          >
            Privacy <span className="text-brand">Policy</span>
          </h1>
          <p
            className="mt-4 text-white/40 text-sm"
            style={{
              opacity: heroVisible ? 1 : 0,
              transition: "opacity 0.6s ease-out 0.5s",
            }}
          >
            Last updated: April 20, 2026
          </p>
        </div>
        <div className="absolute bottom-0 left-0 w-full h-24 bg-gradient-to-t from-white to-transparent z-[1]" />
      </section>

      {/* Content */}
      <section className="bg-white py-16 sm:py-24">
        <div className="mx-auto max-w-3xl px-6 sm:px-12">
          <AnimatedSection>
            <div className="prose prose-zinc prose-lg max-w-none prose-headings:font-extrabold prose-headings:text-zinc-900 prose-h2:text-2xl prose-h2:mt-12 prose-h2:mb-4 prose-h2:border-l-4 prose-h2:border-brand prose-h2:pl-4 prose-h3:text-xl prose-h3:mt-8 prose-h3:mb-3 prose-p:text-zinc-600 prose-p:leading-relaxed prose-a:text-brand prose-a:font-semibold prose-a:no-underline hover:prose-a:underline prose-strong:text-zinc-800 prose-ul:text-zinc-600 prose-ul:list-disc prose-ul:pl-6 prose-ul:my-4 prose-li:my-1 prose-li:marker:text-brand">
              <h2>Interpretation and Definitions</h2>
              <p>
                The words of which the initial letter is capitalized have
                meanings defined under the following conditions. The following
                definitions shall have the same meaning regardless of whether
                they appear in singular or plural.
              </p>
              <p>For the purposes of this Privacy Policy:</p>
              <ul className="list-disc pl-6 my-4 space-y-1">
                <li>
                  <strong>Company</strong> (referred to as &quot;the
                  Company&quot;, &quot;We&quot;, &quot;Us&quot; or
                  &quot;Our&quot;) refers to Volz Method Piano Lessons.
                </li>
                <li>
                  <strong>Device</strong> means any device that can access the
                  Service such as a computer, a cellphone, or a digital tablet.
                </li>
                <li>
                  <strong>Personal Data</strong> is any information that relates
                  to an identified or identifiable individual.
                </li>
                <li>
                  <strong>Service</strong> refers to the Website and all
                  related services, including in-home piano lessons and
                  communication systems.
                </li>
                <li>
                  <strong>Service Provider</strong> means any natural or legal
                  person who processes the data on behalf of the Company.
                </li>
                <li>
                  <strong>Usage Data</strong> refers to data collected
                  automatically, either generated by the use of the Service or
                  from the Service infrastructure itself.
                </li>
                <li>
                  <strong>You</strong> means the individual accessing or using
                  the Service.
                </li>
              </ul>

              <h2>Collecting and Using Your Personal Data</h2>

              <h3>Types of Data Collected</h3>
              <p>
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. This may include, but is not limited
                to:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-1">
                <li>First and last name</li>
                <li>Email address</li>
                <li>Phone number</li>
                <li>Address/location details (for in-home lesson scheduling)</li>
                <li>Student information (e.g., age, experience level)</li>
                <li>Personal preferences related to lessons</li>
              </ul>

              <h3>Use of Your Personal Data</h3>
              <p>
                The Company may use Personal Data for the following purposes:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-1">
                <li>To provide and maintain our Service</li>
                <li>To schedule and deliver in-home piano lessons</li>
                <li>To manage Your Account</li>
                <li>For the performance of a contract</li>
                <li>
                  To contact You by email, phone calls, or SMS regarding
                  lessons, scheduling, billing, or updates
                </li>
                <li>To send promotional offers (only if consent is provided)</li>
                <li>To improve our services through data analysis</li>
                <li>To manage customer service requests</li>
              </ul>

              <h2>Sharing of Your Personal Data (Updated for TCR Compliance)</h2>
              <p>
                We may share your information with Service Providers only as
                necessary to operate our business (e.g., scheduling software,
                payment processors, messaging platforms).
              </p>
              <p>
                <strong>We do NOT sell your personal data.</strong>
              </p>
              <p>
                Mobile Opt-in, SMS consent, and phone numbers collected for SMS
                communication purposes will <strong>NOT</strong> be shared with
                any third party or affiliates for marketing purposes.
              </p>

              <h2>Retention of Your Personal Data</h2>
              <p>
                We retain Personal Data only as long as necessary to fulfill
                the purposes outlined in this Privacy Policy, comply with legal
                obligations, resolve disputes, and enforce agreements.
              </p>

              <h2>Transfer of Your Personal Data</h2>
              <p>
                Your data may be processed in locations outside your state or
                country. We take all reasonable steps to ensure your data is
                treated securely and in accordance with this Privacy Policy.
              </p>

              <h2>Disclosure of Your Personal Data</h2>
              <h3>Law Enforcement</h3>
              <p>
                We may disclose Personal Data if required by law.
              </p>
              <h3>Other Legal Requirements</h3>
              <p>We may disclose data to:</p>
              <ul className="list-disc pl-6 my-4 space-y-1">
                <li>Comply with legal obligations</li>
                <li>Protect company rights or property</li>
                <li>Prevent wrongdoing</li>
                <li>Protect user safety</li>
                <li>Defend against legal liability</li>
              </ul>

              <h2>Security of Your Personal Data</h2>
              <p>
                We use commercially reasonable methods to protect your data but
                cannot guarantee absolute security.
              </p>

              <h2>Links to Other Websites</h2>
              <p>
                We are not responsible for third-party websites linked from our
                Service.
              </p>

              <h2>Changes to This Privacy Policy</h2>
              <p>
                We may update this policy at any time. Changes take effect when
                posted.
              </p>

              <h2>SMS Terms &amp; Conditions (TCR Compliant)</h2>

              <h3>SMS Consent Communication</h3>
              <p>
                Phone numbers collected as part of the SMS consent process will
                not be shared with third parties for marketing purposes.
              </p>

              <h3>Types of SMS Communications</h3>
              <p>
                If you have consented to receive SMS messages from Volz Method
                Piano Lessons, you may receive messages related to:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-1">
                <li>Lesson reminders</li>
                <li>Scheduling updates</li>
                <li>Follow-up messages</li>
                <li>Billing notifications</li>
                <li>Promotions or offers (if opted in)</li>
              </ul>
              <p>
                <strong>Example:</strong>
                <br />
                &ldquo;Hello, this is a reminder of your upcoming piano lesson
                on Tuesday at 4:00 PM. Reply STOP to opt out at any time.&rdquo;
              </p>

              <h3>Message Frequency</h3>
              <p>
                Message frequency may vary depending on your interaction with
                us.
              </p>
              <p>
                <strong>Example:</strong>
                <br />
                You may receive up to 2&ndash;4 SMS messages per week related
                to lessons, scheduling, or your account.
              </p>

              <h3>Potential Fees for SMS Messaging</h3>
              <p>
                Standard message and data rates may apply based on your
                carrier&rsquo;s plan.
              </p>

              <h3>Opt-In Methods</h3>
              <p>
                You may opt in to receive SMS messages from Volz Method Piano
                Lessons in the following ways:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-1">
                <li>Verbally during a phone or in-person conversation</li>
                <li>By submitting an online form on our website</li>
                <li>By checking an SMS consent box on a form</li>
                <li>By filling out a paper form</li>
              </ul>

              <h3>Opt-Out Method</h3>
              <p>
                You can opt out at any time by replying <strong>STOP</strong> to
                any SMS message.
                <br />
                You may also contact us directly to be removed.
              </p>

              <h3>Help</h3>
              <p>
                If you are experiencing issues, reply <strong>HELP</strong> or
                contact us at:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-1">
                <li>
                  Phone:{" "}
                  <a href="tel:+13854820122">385-482-0122</a>
                </li>
                <li>
                  Email:{" "}
                  <a href="mailto:support@volzpiano.com">
                    support@volzpiano.com
                  </a>
                </li>
                <li>
                  Website:{" "}
                  <a href="https://www.volzpiano.com">
                    https://www.volzpiano.com
                  </a>
                </li>
              </ul>

              <h3>Additional Options</h3>
              <p>
                You may choose not to receive SMS messages by not selecting the
                SMS consent option on our forms.
              </p>

              <h3>Standard Messaging Disclosures</h3>
              <ul className="list-disc pl-6 my-4 space-y-1">
                <li>Message and data rates may apply</li>
                <li>You can opt out at any time by texting STOP</li>
                <li>For help, text HELP or contact us directly</li>
                <li>Message frequency may vary</li>
              </ul>

              <h2>Contact Us</h2>
              <p>
                If you have any questions about this Privacy Policy, you can
                contact us:
              </p>
              <ul className="list-disc pl-6 my-4 space-y-1">
                <li>
                  Email:{" "}
                  <a href="mailto:support@volzpiano.com">
                    support@volzpiano.com
                  </a>
                </li>
                <li>
                  Phone:{" "}
                  <a href="tel:+13854820122">385-482-0122</a>
                </li>
                <li>
                  Website:{" "}
                  <a href="https://www.volzpiano.com">
                    https://www.volzpiano.com
                  </a>
                </li>
              </ul>
            </div>
          </AnimatedSection>
        </div>
      </section>
    </main>
  );
}
