"use client";

import { useEffect, useState } from "react";
import AnimatedSection from "@/app/components/AnimatedSection";

export default function PrivacyPolicyPage() {
  const [heroVisible, setHeroVisible] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setHeroVisible(true), 100);
    return () => clearTimeout(t);
  }, []);

  return (
    <main>
      {/* Hero */}
      <section className="relative flex min-h-[35vh] items-center justify-center overflow-hidden bg-zinc-900 pt-24">
        <div
          className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 h-72 w-[500px] rounded-full opacity-15 blur-[120px]"
          style={{
            background: "radial-gradient(circle, #6343d4 0%, transparent 70%)",
          }}
        />
        <div className="relative z-[2] text-center px-6">
          <h1
            className="text-4xl font-extrabold text-white sm:text-5xl lg:text-6xl"
            style={{
              opacity: heroVisible ? 1 : 0,
              transform: heroVisible ? "translateY(0)" : "translateY(30px)",
              transition: "all 0.8s ease-out 0.2s",
              textShadow: "0 4px 24px rgba(0,0,0,0.5)",
            }}
          >
            Privacy <span className="text-brand">Policy</span>
          </h1>
          <p
            className="mt-4 text-white/40 text-sm"
            style={{
              opacity: heroVisible ? 1 : 0,
              transition: "opacity 0.6s ease-out 0.5s",
            }}
          >
            Last updated: July 31, 2024
          </p>
        </div>
        <div className="absolute bottom-0 left-0 w-full h-24 bg-gradient-to-t from-white to-transparent z-[1]" />
      </section>

      {/* Content */}
      <section className="bg-white py-16 sm:py-24">
        <div className="mx-auto max-w-3xl px-6 sm:px-12">
          <AnimatedSection>
            <div className="prose prose-zinc prose-lg max-w-none prose-headings:font-extrabold prose-headings:text-zinc-900 prose-h2:text-2xl prose-h2:mt-12 prose-h2:mb-4 prose-h2:border-l-4 prose-h2:border-brand prose-h2:pl-4 prose-p:text-zinc-600 prose-p:leading-relaxed prose-a:text-brand prose-a:font-semibold prose-a:no-underline hover:prose-a:underline prose-strong:text-zinc-800 prose-ul:text-zinc-600 prose-li:marker:text-brand">
              <h2>Interpretation and Definitions</h2>
              <p>
                The words of which the initial letter is capitalized have
                meanings defined under the following conditions. The following
                definitions shall have the same meaning regardless of whether
                they appear in singular or in plural.
              </p>
              <p>For the purposes of this Privacy Policy:</p>
              <ul>
                <li>
                  <strong>Company</strong> (referred to as &quot;the
                  Company&quot;, &quot;We&quot;, &quot;Us&quot; or
                  &quot;Our&quot;) refers to Volz Method Piano Lessons.
                </li>
                <li>
                  <strong>Device</strong> means any device that can access the
                  Service such as a computer, a cellphone, or a digital tablet.
                </li>
                <li>
                  <strong>Personal Data</strong> is any information that relates
                  to an identified or identifiable individual.
                </li>
                <li>
                  <strong>Service</strong> refers to the Website.
                </li>
                <li>
                  <strong>Service Provider</strong> means any natural or legal
                  person who processes the data on behalf of the Company.
                </li>
                <li>
                  <strong>Usage Data</strong> refers to data collected
                  automatically, either generated by the use of the Service or
                  from the Service infrastructure itself.
                </li>
                <li>
                  <strong>You</strong> means the individual accessing or using
                  the Service.
                </li>
              </ul>

              <h2>Collecting and Using Your Personal Data</h2>
              <h3>Types of Data Collected</h3>
              <p>
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. Personally identifiable information may
                include, but is not limited to:
              </p>
              <ul>
                <li>First name and last name</li>
                <li>Email address</li>
                <li>Phone number</li>
                <li>Location details</li>
                <li>Personal preferences</li>
              </ul>

              <h3>Use of Your Personal Data</h3>
              <p>
                The Company may use Personal Data for the following purposes:
              </p>
              <ul>
                <li>
                  To provide and maintain our Service, including to monitor the
                  usage of our Service.
                </li>
                <li>
                  To manage Your Account and registration as a user of the
                  Service.
                </li>
                <li>
                  For the performance of a contract with You.
                </li>
                <li>
                  To contact You by email, telephone calls, SMS, or other forms
                  of electronic communication.
                </li>
                <li>
                  To provide You with news, special offers, and general
                  information about other services which we offer.
                </li>
                <li>To manage Your requests.</li>
                <li>
                  For other purposes such as data analysis, identifying usage
                  trends, and improving our Service.
                </li>
              </ul>

              <h2>Retention of Your Personal Data</h2>
              <p>
                The Company will retain Your Personal Data only for as long as
                is necessary for the purposes set out in this Privacy Policy. We
                will retain and use Your Personal Data to the extent necessary
                to comply with our legal obligations, resolve disputes, and
                enforce our agreements and policies.
              </p>

              <h2>Transfer of Your Personal Data</h2>
              <p>
                Your information, including Personal Data, is processed at the
                Company&apos;s operating offices and in any other places where
                the parties involved in the processing are located. The Company
                will take all steps reasonably necessary to ensure that Your
                data is treated securely and in accordance with this Privacy
                Policy.
              </p>

              <h2>Disclosure of Your Personal Data</h2>
              <h3>Law Enforcement</h3>
              <p>
                Under certain circumstances, the Company may be required to
                disclose Your Personal Data if required to do so by law or in
                response to valid requests by public authorities.
              </p>
              <h3>Other Legal Requirements</h3>
              <p>
                The Company may disclose Your Personal Data in the good faith
                belief that such action is necessary to:
              </p>
              <ul>
                <li>Comply with a legal obligation</li>
                <li>
                  Protect and defend the rights or property of the Company
                </li>
                <li>
                  Prevent or investigate possible wrongdoing in connection with
                  the Service
                </li>
                <li>
                  Protect the personal safety of Users of the Service or the
                  public
                </li>
                <li>Protect against legal liability</li>
              </ul>

              <h2>Security of Your Personal Data</h2>
              <p>
                The security of Your Personal Data is important to Us, but
                remember that no method of transmission over the Internet, or
                method of electronic storage is 100% secure. While We strive to
                use commercially acceptable means to protect Your Personal Data,
                We cannot guarantee its absolute security.
              </p>

              <h2>Links to Other Websites</h2>
              <p>
                Our Service may contain links to other websites that are not
                operated by Us. If You click on a third party link, You will be
                directed to that third party&apos;s site. We strongly advise You
                to review the Privacy Policy of every site You visit. We have no
                control over and assume no responsibility for the content,
                privacy policies, or practices of any third party sites or
                services.
              </p>

              <h2>Changes to This Privacy Policy</h2>
              <p>
                We may update Our Privacy Policy from time to time. We will
                notify You of any changes by posting the new Privacy Policy on
                this page. Changes are effective when they are posted on this
                page.
              </p>

              <h2>SMS Terms &amp; Conditions</h2>
              <p>
                By opting in to SMS communications from Volz Method Piano
                Lessons, you agree to receive text messages related to your
                account, lesson reminders, promotional offers, and other
                communications. Message frequency may vary. Message and data
                rates may apply. You can opt out at any time by texting STOP.
                For help, text HELP or contact us at 385-482-0122.
              </p>

              <h2>Contact Us</h2>
              <p>
                If you have any questions about this Privacy Policy, You can
                contact us by email at:{" "}
                <a href="mailto:support@volzpiano.com">
                  support@volzpiano.com
                </a>
              </p>
            </div>
          </AnimatedSection>
        </div>
      </section>
    </main>
  );
}
